/*
 * Nature API
 *
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApplianceModelAndParamsInner {
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<Box<crate::models::ApplianceModelAndParamsInnerModel>>,
    #[serde(rename = "params", skip_serializing_if = "Option::is_none")]
    pub params: Option<Box<crate::models::ApplianceModelAndParamsInnerParams>>,
}

impl ApplianceModelAndParamsInner {
    pub fn new() -> ApplianceModelAndParamsInner {
        ApplianceModelAndParamsInner {
            model: None,
            params: None,
        }
    }
}


