/*
 * Nature API
 *
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApplianceModelAndParamsInnerModel {
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "image", skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    #[serde(rename = "manufacturer", skip_serializing_if = "Option::is_none")]
    pub manufacturer: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "remote_name", skip_serializing_if = "Option::is_none")]
    pub remote_name: Option<String>,
    #[serde(rename = "series", skip_serializing_if = "Option::is_none")]
    pub series: Option<String>,
}

impl ApplianceModelAndParamsInnerModel {
    pub fn new() -> ApplianceModelAndParamsInnerModel {
        ApplianceModelAndParamsInnerModel {
            country: None,
            id: None,
            image: None,
            manufacturer: None,
            name: None,
            remote_name: None,
            series: None,
        }
    }
}


