/*
 * Nature API
 *
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserResponseUpdatedPrivacyPolicyLinksValue {
    #[serde(rename = "link", skip_serializing_if = "Option::is_none")]
    pub link: Option<String>,
    #[serde(rename = "text", skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
}

impl UserResponseUpdatedPrivacyPolicyLinksValue {
    pub fn new() -> UserResponseUpdatedPrivacyPolicyLinksValue {
        UserResponseUpdatedPrivacyPolicyLinksValue {
            link: None,
            text: None,
        }
    }
}


